/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.freefair.lombok") version "6.4.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val hibernateVersion: String by project
val h2databaseVersion: String by project
val junitVersion: String by project

dependencies {
    implementation("org.hibernate:hibernate-core:$hibernateVersion")
    implementation("com.h2database:h2:$h2databaseVersion")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:$junitVersion")
}

application {
    // Define the main class for the application.
    mainClass.set("hello.jpa.java.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
